### ISSUE TITLE
how can I use other port?

### ISSUE THREAD

**Issue by John3** [vlsi/ksar#104]
Hi

I'm using the ssh command to see the sar files,  but not sure how to use other port.

thanks

**Comment by Pitterling** [comment]
specify the port behind the hostname separated by : 
e.g. root@host1:24

if you don't specify an port, port 22 (standard ssh port) will be set. 
[CnxHistory --> specify port](https://github.com/vlsi/ksar/blob/c14f9340208027fe54a2803c921ee9dcad07c2ca/src/main/java/net/atomique/ksar/xml/CnxHistory.java#L26)

does it mean, that your ssh daemon is not running on the default port 22 ?

**Comment by John3** [comment]
Thanks I was using it that way, and it don't worked, but I found the problem, not related to sar :)

**Comment by John3** [comment]
BTW good work mate :P keep doing that. :+1:

**Comment by Pitterling** [comment]
thx, credits go to all contributors
