### ISSUE TITLE
Window doesn't respect placement

### ISSUE THREAD

**Issue by Luticus** [vlsi/ksar#116]
When launched, at least under KDE 5, the splash and main window do not respect KDE's placement and will appear in odd places in multi monitor setups.  On my desktop with 4 monitors the main window appears almost entirely off screen and is sized to be very big.  I know it's nit picky but every time I launch the application I have to move it so it can be used.  Would be nice if it would open with a respectable size (fits on one monitor) and is at least centered on one monitor, preferably where the mouse is.  If not there then on the primary monitor, and in the worst case, just centered on whatever monitor.

**Comment by Pitterling** [comment]
This is done within the [Desktop constructor](https://github.com/vlsi/ksar/blob/master/src/main/java/net/atomique/ksar/ui/Desktop.java#L28)
This code has never touched since 2010 .... 

```java
  public Desktop() {
    int wmargins = 90;
    int hmargins = 60;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    initComponents();
    setBounds(wmargins, hmargins, screenSize.width - (wmargins * 2),
        screenSize.height - (hmargins * 2));

    DesktopPane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    setVisible(true);
  }
```

In my case (windows 3 multi-monitor) its always displayed on the main screen respecting the defined margins. 
![image](https://user-images.githubusercontent.com/4181164/32958087-b664a036-cbbd-11e7-992b-1e2fbce591a1.png)

What is reported in your case ?

**Comment by Luticus** [comment]
I have 3 separate examples.  The first is a Debian 9/KDE 5 four monitor system.  On this box the splash appears centered, but the main window appears large and off to the upper left.  The second is a Laptop running centos and KDE 4, in the case of a single monitor, everything is fine.  In the case of dual monitors, the splash window appears in the middle of the two monitors as if it is treating them as one big unified screen, and the main window appears off to the left, but is not positioned correctly so what happens is that the app hangs over onto the right screen a bit.  It's not a show stopper, the app is completely usable, it would just be nice to not have to move them every time.

**Comment by Luticus** [comment]
If the app has only been designed to account for window placement on a windows desktop then this might not be something that can be done easily.  I'm not sure how to go about it myself but I am looking into it.  I even tried kde's ability to force windows to behave if they are considered "unmanaged" but in both 4 and 5 it doesn't seem to have much of an effect, yet.

**Comment by Pitterling** [comment]
this has not been designed for windows only .. its just to old that it respected multi-monitor support :)

I believe this might be your issue [Rendering in a Multi-Screen Environment](http://download.oracle.com/otn_hosted_doc/jdeveloper/904preview/jdk14doc/docs/guide/2d/spec/j2d-awt.fm6.html)

Do you have the chance to debug to the mentioned code line and check for the reported screen size?

**Comment by Pitterling** [comment]
Could you please run the attached jar version (remove the .zip file extension)
[ksar-5.2.4-SNAPSHOT-all.jar.zip](https://github.com/vlsi/ksar/files/1483383/ksar-5.2.4-SNAPSHOT-all.jar.zip)

and provide the ksar_all.log output .. it should contain entries like this:

```
net.atomique.ksar.ui.Desktop - Screensize: java.awt.Dimension[width=1920,height=1200]
net.atomique.ksar.ui.Desktop - Screensize Screen[0][0]: java.awt.Rectangle[x=0,y=0,width=1920,height=1200]
net.atomique.ksar.ui.Desktop - Screensize Screen[1][0]: java.awt.Rectangle[x=1920,y=0,width=1920,height=1200]
net.atomique.ksar.ui.Desktop - Screensize Screen[2][0]: java.awt.Rectangle[x=-1920,y=109,width=1920,height=1080]]
```

**Comment by Luticus** [comment]
Here's the log output, this was taken from a 4 monitor Debian 9 system running KDE 5.  The montors are in this configuration:

    X       [1080] 
[1080] [    4K    ] [1080]

The main window appears about where that X is located and over hangs into the other monitors around it making it much easier to move.  The splash is also off as it seems to simply appear in the center of the entire set of monitors.  So in my case here it would be on the 4k monitor, slightly higher than the center of that screen, where as on a dual monitor system it appears halfway on the two screens, in the middle.  The main window always appears off to the left somewhere close to but not exactly on the 0,0 point.

[ksar_all.log](https://github.com/vlsi/ksar/files/1483427/ksar_all.log)

**Comment by Pitterling** [comment]
it seems that KDE returns the virtual coordinates .. even if there is no screen device
```
Screensize: java.awt.Dimension[width=7680,height=3240]
Screen[0][0]: java.awt.Rectangle[x=1920,y=1080,width=3840,height=2160]
Screen[1][0]: java.awt.Rectangle[x=5760,y=1898,width=1920,height=1080]
Screen[2][0]: java.awt.Rectangle[x=2880,y=0,width=1920,height=1080]
Screen[3][0]: java.awt.Rectangle[x=0,y=1956,width=1920,height=1080]
``` 

try this one - it will always only use the boundaries of screen[0] (in your case your 4K)
[ksar-5.2.4-SNAPSHOT-all.jar.zip](https://github.com/vlsi/ksar/files/1484184/ksar-5.2.4-SNAPSHOT-all.jar.zip)

**Comment by Luticus** [comment]
Sorry I couldn't get back to you sooner, went out of town over the weekend.  Looks like your code fixed the main window on my laptop with dual monitors.  I made sure to disable any KDE rules too so it should be good.  I'll test the 4 monitor setup when I get home this afternoon.  The splash screen, however, is still broken on the dual monitor setup.  It still appears right in the middle of them.

**Comment by Luticus** [comment]
Sorry wanted to test the 4 monitor situation last night for you but got busy with Thanksgiving prep stuff so couldn't get around to it, I'll test it out tonight and let you know how it works.

**Comment by Luticus** [comment]
I can confirm that the main window shows centered on the primary monitor in the case of both my 4k quad monitor setup, as well as my laptop with dual monitors.  The splash still misbehaves but that's just an aesthetic thing.  The program is, overall, much nicer for me to use now.  Thanks for looking into this!

**Comment by Luticus** [comment]
oh, did just realize that child windows misbehave too though.  Like the about popup and the system preferences dialogue.  They appear off screen and up to the left as the main window used to.  Might want to check that out.

**Comment by Pitterling** [comment]
well, yes that's a mess since 5.1beta .. try this build .. this should fix all dialogs

[ksar-5.2.4-SNAPSHOT-all.jar.zip](https://github.com/vlsi/ksar/files/1497727/ksar-5.2.4-SNAPSHOT-all.jar.zip)

**Comment by Luticus** [comment]
Yes, that seems to fix all dialogs, epic!  Thanks!

**Comment by Pitterling** [comment]
Thanks for your help!
