### ISSUE TITLE
Process multiple sar files from command line

### ISSUE THREAD

**Issue by stefvanvlierberghe** [vlsi/ksar#118]
It seems that in older versions it was possible to open multiple sar files and they all remained in sync (i.e. selecting/showing CPU on one display would open CPU on all other displays).

This was a handy feature : https://sourceforge.net/p/ksar/support-requests/13/

With the new version even -help is broken: 
vvl@dhws029> java -jar ksar-5.2.3-all.jar -help
ksar Version : 5.2.3

The old version help used to show:
-input <arg>: argument must be either ssh://user@host/command or cmd://command or file://path/to/file or just /path/to/file

I hope these regressions are non-intentional and are still available.

**Comment by Pitterling** [comment]
this is not available since the 5.1 beta versions, which were complete code rewrite by the former authors .. not all functionality from 5.0.6 has been re-implemented ..

Command-line options help will come soon, but specifying multiple files will take a while

**Comment by stefvanvlierberghe** [comment]
Ok, thanks for the info, we will stick to 5.0.6 until the rewrite is complete.

.

____

This message and any files transmitted with it are legally privileged and intended for the sole use of the individual(s) or entity to whom they are addressed. If you are not the intended recipient, please notify the sender by reply and delete the message and any attachments from your system. Any unauthorised use or disclosure of the content of this message is strictly prohibited and may be unlawful.

Nothing in this e-mail message amounts to a contractual or legal commitment on the part of EUROCONTROL, unless it is confirmed by appropriately signed hard copy.

Any views expressed in this message are those of the sender.

**Comment by rschuster** [comment]
concatenate the files together first the open the one large file seems to work.

find . -name "sar*" -exec cat {} >> file \;

The open file in ksar.

**Comment by stefvanvlierberghe** [comment]
Thanks, didn't realize it was that simple :-)
