### ISSUE TITLE
Looking for command line feature for generating reports in PNG and PDF.

### ISSUE THREAD

**Issue by chikkalain** [vlsi/ksar#122]
In older version , I found report generation in PNG and PDF ,But the new version I did not find these feature. I am looking similar NMON command line fir KSAR also . 

https://nmonvisualizer.github.io/nmonvisualizer/commandline.html

**Comment by chikkalain** [comment]
5.0.6 has these feature 

https://en.wikipedia.org/wiki/Ksar_(Unix_sar_grapher)

**Comment by Pitterling** [comment]
duplicate of #63
