### ISSUE TITLE
Unable to parse date from SunOS 11.3

### ISSUE THREAD

**Issue by DenisSlnn** [vlsi/ksar#142]
Hello, here is logfile 
[ksar_all.log](https://github.com/vlsi/ksar/files/2056901/ksar_all.log)
ksar unable to parse date from SunOS 11.3 with date like 05/16/2018
older ksar 5.0.4 don't have such issue:
```
Sar Info:

 

OS Type: SunOS (automatically detected)

OS Version: 5.11

Kernel Release: 11.3

CPU Type: sun4v

Hostname:

Start of SAR: 05/16/2018

End of SAR: 05/16/2018

 

 

Time range information:

First data point: Wed May 16 00:00:00 ALMT 2018

Last data point: Wed May 16 23:50:00 ALMT 2018

 

Graph range:

First data point: Wed May 16 00:00:00 ALMT 2018

Last data point: Wed May 16 23:50:00 ALMT 2018
```

**Comment by Pitterling** [comment]
Please provide your file.

Also be reminded, no one looked to the Solaris code path for the last 8 years ...

**Comment by DenisSlnn** [comment]
Well, it's original Solaris SPARC 11.3
[sar26.zip](https://github.com/vlsi/ksar/files/2057494/sar26.zip)

**Comment by Pitterling** [comment]
well, not everyone has a solaris testsystem available
 .. even more my last contact with SPARC is decades ago 😃 

please try [v5.2.4-snapshot-4d0d986](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot-4d0d986)

**Comment by DenisSlnn** [comment]
Thanks a lot, it works. But another issue is  with opening overdetailed SAR file, with 1min collection interval. Program starts lagging after importing ~ 5 hour and completely hang around 12 hour importing :) Tested on Solaris 11.3 SAR and Linux RHEL SAR files, on high productivity servers. Looks like it is about CPU's and disks count (over 256 Cores and ~50 disks).
