### ISSUE TITLE
Issue is with opening overdetailed SAR file

### ISSUE THREAD

**Issue by DenisSlnn** [vlsi/ksar#144]
Issue is with opening overdetailed SAR file, with 1min collection interval. Program starts lagging after importing ~ 5 hour and completely hang around 12 hour importing :) Tested on Solaris 11.3 SAR and Linux RHEL SAR files, on high productivity servers. Looks like it is about CPU's and disks count (over 256 Cores and ~50 disks).
[sar20.zip](https://github.com/vlsi/ksar/files/2061911/sar20.zip)

**Comment by Pitterling** [comment]
My files usually have finer granularity than 1min and even more CPUs and they are processed in reasonable time.

Are you using 64bit Java runtime?

**Comment by DenisSlnn** [comment]
No, only 32bit, jre-8u171. I will try 64 and then update issue.

**Comment by DenisSlnn** [comment]
UPDATE:
`java -version

java version "1.8.0_171"

Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

 

java -jar ksar-5.2.4-SNAPSHOT-all.jar

15:03:57.310 [main] TRACE net.atomique.ksar.Main - main - Start

15:03:57.314 [main] TRACE net.atomique.ksar.Main - Java runtime Version : 1.8.0_171-b11

15:03:57.316 [main] TRACE net.atomique.ksar.Main - ksar Version : 5.2.4

15:03:57.317 [main] TRACE net.atomique.ksar.GlobalOptions - load Config

ш■э 01, 2018 3:03:57 PM java.util.prefs.WindowsPreferences <init>

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

15:03:57.437 [main] TRACE net.atomique.ksar.GlobalOptions - load GlobalOptions

15:03:57.503 [main] TRACE net.atomique.ksar.Main - MainScreen

15:03:57.532 [AWT-EventQueue-0] TRACE net.atomique.ksar.ui.Desktop - screen [0] boundaries: java.awt.Rectangle[x=0,y=0,width=1920,height=1200]

15:03:57.629 [AWT-EventQueue-0] TRACE net.atomique.ksar.ui.Desktop - desktop window boundaries: java.awt.Rectangle[x=90,y=60,width=1740,height=1080]

15:04:02.272 [Thread-3] DEBUG net.atomique.ksar.parser.Linux - askDateFormat - provide date format

15:05:06.726 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %irq

15:05:06.727 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %soft

15:05:06.729 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %guest

15:05:06.758 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %irq

15:05:06.758 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %soft

15:05:06.760 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %guest

15:05:06.767 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %irq

15:05:06.767 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %soft

15:05:06.769 [AWT-EventQueue-0] WARN  net.atomique.ksar.GlobalOptions - color not found for tag %guest
`
And so on, a LOT of this messages.

**Comment by Pitterling** [comment]
what do you mean by 98% load ... if you see the color not found WARN messages, everything has been loaded. The WARN messages just indicate that there is no fixed color definition.

If you click on the parent nodes with long list of childs (like CPU,Devices) in your case .. it takes a while to draw the picture .. that's it. 

Beside that everything works as expected.

**Comment by Pitterling** [comment]
last data in file is 
11:53:01 PM         0      0.00      0.00      0.00      0.00      0.00      0.00

The WARN messages come from the graph drawing functionality. Therefore all the data has been loaded.

I just provided a new jar file .. adding all colors ... but this is not performance critical.
[v5.2.4-snapshot-d08700a - Adding colors](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot-d08700a)

Again if you click directly on a parent node like CPU .. all graphs will be prepared in background and then drawn at one .. this will take while. Therefore please open the node (+ sign) and select a single entry

**Comment by Pitterling** [comment]
CPU node uses up to 3.6 GiB memory to draw all CPU graphs on my system. 
The latest [pre-release](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot-72f2da0) also logs the bitness of your java runtime.

Let me know, if i can close this?

**Comment by DenisSlnn** [comment]
Well, thanks! Close issue.
