### ISSUE TITLE
QUESTION: Documentation for XML Graph Syntax available?

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#15]
is somewhere documentation available what "**type, format base, factor**" mean?

``` xml
            <Graph name="KMEM2" Title="KMem" type="unique">
                <Plot Title="KMem">
                    <cols>kbmemfree kbmemused kbbuffers kbcached kbcommit kbactive kbinact kbdirty</cols>
                    <format base="1024" factor="1024"></format>
                </Plot>
                <Plot Title="%">
                    <cols>%memused %commit</cols>
                </Plot>
            </Graph>
```

**Comment by ynamiki** [comment]
Unfortunately, There is no document.

From my understanding:

- type

  Whether a graph has multiple sheets ("multiple") or not ("unique").
  If type is "multiple", a folder icon is shown in the GUI (like graphs for CPU, Devices, ....)

- format/base

  If "1024" is specified, a numeric value (in an output of `sar`) will be formatted as described below in a graph.

- format/factor

  An multiplier for a numeric value.
  An axis of the graph is printed in "human readable" format: 1 KB, 1 MB, ...

If a value is expressed in kilobyte (e.g. kbmemused, etc.), add `<format base="1024" factor="1024"></format>` for the column.

**Comment by Pitterling** [comment]
Plots are also ordered by characters (title), not by definition - below example 
is shown in this ordering **"bytes, cast, packet, util"**
Any chance to change that?

```xml
<Graph name="INET1" Title="Interfaces traffic" type="multiple">
     <Plot Title="packet">
       <cols>rxpck/s txpck/s</cols>
     </Plot>
     <Plot Title="bytes">
       <cols>rxbyt/s txbyt/s rxkB/s txkB/s</cols>
     </Plot>
     <Plot Title="cast">
       <cols>rxcmp/s txcmp/s rxmcst/s</cols>
     </Plot>
     <Plot Title="util">
       <cols>%ifutil</cols>
     </Plot>
</Graph>
```
