### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ramarov** [vlsi/ksar#151]
Unable to load output from sar -A. Seeing following error in the console

C:\tmp>java -jar ksar-5.2.4-SNAPSHOT-all.jar
09:55:49.268 [main] TRACE net.atomique.ksar.Main - main - Start
09:55:49.272 [main] TRACE net.atomique.ksar.Main - Java runtime Version : 1.8.0_77-b03
09:55:49.272 [main] TRACE net.atomique.ksar.Main - Java runtime architecture : amd64
09:55:49.273 [main] TRACE net.atomique.ksar.Main - ksar Version : 5.2.4
09:55:49.274 [main] TRACE net.atomique.ksar.GlobalOptions - load Config
09:55:49.376 [main] TRACE net.atomique.ksar.GlobalOptions - load GlobalOptions
09:55:49.433 [main] TRACE net.atomique.ksar.Main - MainScreen
09:55:49.453 [AWT-EventQueue-0] TRACE net.atomique.ksar.ui.Desktop - screen [0] boundaries: java.awt.Rectangle[x=0,y=0,width=1366,height=768]
09:55:49.454 [AWT-EventQueue-0] TRACE net.atomique.ksar.ui.Desktop - screen [1] boundaries: java.awt.Rectangle[x=1366,y=0,width=1920,height=1080]
09:55:49.529 [AWT-EventQueue-0] TRACE net.atomique.ksar.ui.Desktop - desktop window boundaries: java.awt.Rectangle[x=90,y=60,width=1186,height=648]
09:56:02.013 [Thread-3] DEBUG net.atomique.ksar.parser.Linux - askDateFormat - provide date format
**Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 1
        at net.atomique.ksar.parser.Linux.parse(Linux.java:116)
        at net.atomique.ksar.kSar.parse(kSar.java:145)
        at net.atomique.ksar.FileRead.run(FileRead.java:78)**

**Comment by ramarov** [comment]
Sorry I am unable to reproduce this anymore. Please ignore this issue.

**Comment by Pitterling** [comment]
No prob. Just reopen in case of reoccurrence.
