### ISSUE TITLE
CSV export - skips first data column

### ISSUE THREAD

**Issue by Petaris** [vlsi/ksar#161]
The CSV export option for the Load metrics does not include the RunQ data even though it is present in the sar export and is shown in the graph.

This is for version 5.2.4-b270_g6b8f3169-SNAPSHOT

**Comment by Pitterling** [comment]
it also applies for other data, e.g. Kernel VFS - missing dentunusd

```
Date;Kernel VFS file-nr;Kernel VFS inode-nr;Kernel VFS pty-nr;
09/11/18 21:00:11;6336.0;229550.0;2.0;
09/11/18 21:00:21;6384.0;229564.0;2.0;
09/11/18 21:00:31;6432.0;229570.0;2.0;
```

**Comment by Pitterling** [comment]
@Petaris pls try [v5.2.4-snapshot.4-gdae9eee](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot.4-gdae9eee)

**Comment by Petaris** [comment]
@Pitterling v5.2.4-snapshot.4-gdae9eee has fixed the issue for me.  Thank you!
