### ISSUE TITLE
ksar CLI options to output charts 

### ISSUE THREAD

**Issue by askb** [vlsi/ksar#163]
Is it possible to have ksar to output graphs through CLI taking only the sar data as input? This would help with CI/CD env running on the cloud to get all nodes to output a sar file and generate reports at the end of the jobs. Would help developers largly while tesing code on the cloud.

**Comment by Pitterling** [comment]
duplicate of #63

first we need to get the cmd line handling refactored .. several attempts were made .. i prefer to use an external library to get our coding clean and focused
