### ISSUE TITLE
Request to have %util for the device

### ISSUE THREAD

**Issue by lingyanmeng** [vlsi/ksar#179]
May I ask why we removed the %util, as it's a very helpful indicator for disk monitoring.
Would you please add it back?

The change is made by:
https://github.com/vlsi/ksar/commit/7664e8949d1b8572ea99dfa7a582ddf0b13c0b07#diff-61eeae5f27d32c0806f8f367f2abfcf3

**Comment by Pitterling** [comment]
%util is a misleading KPI and should not be taken for any analysis. There are a lot of blog posts regarding this topic. KPI will not be added back to chart.

e.g. https://brooker.co.za/blog/2014/07/04/iostat-pct.html


From the sar/iostat man page ..
%util 

Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially. But for devices serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.

**Comment by lingyanmeng** [comment]
Thanks a lot for your prompt response! It helps! 

And for others who have the same question, you may also refer to:

https://github.com/sysstat/sysstat/issues/187
http://sebastien.godard.pagesperso-orange.fr/man_sar.html

It's a defect of sar/iostat.

If you do like to display the %util anyway, you can change the src\main\resources\Linux.xml 
section:
            <Graph name="DEV" Title="Devices (Block)" type="multiple">
and 
            <Graph name="DEV_11.5.7" Title="Devices (Block)" type="multiple">

add
                <Plot Title="Utilization">
                    <cols>%util</cols>
                </Plot>

And then rebuild the ksar.jar.
