### ISSUE TITLE
AIX support - run queue and swap queue

### ISSUE THREAD

**Issue by mmquinte** [vlsi/ksar#201]
Please give solution for missing graphs, run and swap queues, while processing an AIX sar file.
I'm attaching a file to work this issue.
Best regards.
[t1-sar20.txt](https://github.com/vlsi/ksar/files/4600511/t1-sar20.txt)

**Comment by Pitterling** [comment]
@mmquinte 
this is what i have created - ok?
![image](https://user-images.githubusercontent.com/4181164/81613189-4b165900-93de-11ea-8fb9-194f8a234eb8.png)

**Comment by mmquinte** [comment]
It’s perfect.

Best regards.

 

Milton Quinteros Salas

+56 (9) 9230-2025

CEO - Consultor Senior

Advora Chile Ltda.

**Comment by Pitterling** [comment]
[check this out](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot.8-g27d96e7)

**Comment by mmquinte** [comment]
I’m getting the same graphs you sent before, but I’m receiving multiple messages like:

 

13:38:39.662 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:02:00     6.7      95                

13:38:39.663 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:03:00     7.1      97                

13:38:39.664 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:04:00     6.5      97                

13:38:39.664 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:05:00     7.3      95                

13:38:39.664 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:06:00     7.3      97                

13:38:39.665 [Thread-3] ERROR net.atomique.ksar.graph.Graph - Runq col 3 is missing 00:08:00     7.5      97                

…

 

Best regards.

 

Milton Quinteros Salas

+56 (9) 9230-2025

CEO - Consultor Senior

Advora Chile Ltda.

**Comment by Pitterling** [comment]
yes, because of the not existing values for swap --> empty fields
The charts are drawn anyway .. i open a new issue .. but i will not look into this ..
