### ISSUE TITLE
Devices (Block) and I/O doesn't plot graph

### ISSUE THREAD

**Issue by toca-cals** [vlsi/ksar#210]
Metric svctm was removed after sysstat version 12.1.2, and now kSar does not plotter Devices (Block) and I/O graphs

Old metrics (sysstat version 12.0.6)
DEV       tps     rkB/s     wkB/s   areq-sz    aqu-sz     await     svctm     %util

New metrics(sysstat version 12.3.2)
DEV       tps     rkB/s     wkB/s     dkB/s   areq-sz    aqu-sz     await     %util

**Comment by Pitterling** [comment]
Please attach an example file with useful data.

**Comment by toca-cals** [comment]
Follow the example file

Regards
[ksaroutput.20200525123402.zip](https://github.com/vlsi/ksar/files/4677927/ksaroutput.20200525123402.zip)

**Comment by Pitterling** [comment]
fixed by new [v5.2.4-snapshot.9-g6c86a7c](https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot.9-g6c86a7c)

**Comment by toca-cals** [comment]
Thank you Pitt!
Now it's ok.

Regards.

**Comment by toca-cals** [comment]
Hello Pitterling, new version of ubuntu sysstat, and the devices are incomplete again. kSar for example shows the I/O to sdc device, but doesn't show individually  the devices sdc1 and sdc2.
[ksaroutput.20210512100605.txt.zip](https://github.com/vlsi/ksar/files/6467866/ksaroutput.20210512100605.txt.zip)



08:00:07          sdc     47.75   1132.35    859.64      0.00     41.72      0.11      1.93      4.33
08:00:07         sdc1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:00:07         sdc2     47.34   1132.35    859.64      0.00     42.08      0.09      1.93      4.31
08:10:07          sdc     17.41    261.53    150.95      0.00     23.69      0.02      0.86      1.39
08:10:07         sdc1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:10:07         sdc2     17.25    261.53    150.95      0.00     23.91      0.01      0.85      1.37
