### ISSUE TITLE
ERROR net.atomique.ksar.kSar - unknown parser

### ISSUE THREAD

**Issue by pakair** [vlsi/ksar#215]
I d/l the latest jar file and tried to run:

$ java -jar ksar-5.2.4-b369_g27d96e71-SNAPSHOT-all.jar 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
12:02:29.014 [Thread-1] ERROR net.atomique.ksar.kSar - unknown parser

$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)

I created sample data (50 points, 2 sec apart) with:  
$ sar -A -o dbexample.sa 2 50

$ sar -V
sysstat version 11.6.1

Running Linux Mint 19.3 thanks.

**Comment by pakair** [comment]
Seems I need to create a txt file for the data, ex. sar -A 2 50 > dbexample.txt

then I can load the data into ksar.

**Comment by Pitterling** [comment]
kSAR only works on txt files, right
