### ISSUE TITLE
Travis Integration not shown during PR

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#216]
@vlsi the travis check is not shown any longer .. only GH action validation. Travis Build is still triggered. Is the travis integration gone? Do you have the change to edit some settings ?

**Comment by Pitterling** [comment]
CI-Travis is back, but GH-Actions are now failing due to cancellation

![image](https://user-images.githubusercontent.com/4181164/95901869-417d8c80-0d94-11eb-9600-f8bea4811aba.png)

**Comment by vlsi** [comment]
It looks like a GitHub glitch.
So I guess we need to wait for a while

**Comment by vlsi** [comment]
E.g. https://twitter.com/githubstatus/status/1316089690508886018

**Comment by vlsi** [comment]
It seems to be resolved. Sorry for the inconvenience :)
