### ISSUE TITLE
Can't Change CPU Chart Colors

### ISSUE THREAD

**Issue by rschuster** [vlsi/ksar#218]
I've edited the config.xml file but the CPU chart is still default colors. 

Sys and iowait are almost identical and impossible to tell apart. 

Also it would be nice to click to remove metrics from the graph.

**Comment by Pitterling** [comment]
it should work .. see also #107 
src/main/resources/Config.xml

Chart definitions are handled within
src/main/resources/Linux.xml

```xml
            <Graph name="CPU" Title="CPU" type="multiple">
                <Stack Title="Used [%]" size="3">
                    <cols>%usr %user %nice %sys %iowait %steal %irq %soft %guest</cols>
                    <range>0,100</range>
                </Stack>
                <Plot Title="Idle [%]" size="1">
                    <cols>%idle</cols>
                    <range>0,100</range>
                </Plot>
            </Graph>
```

adjust the col property and remove whatever you want ...
