### ISSUE TITLE
Managing Version Number in a Simple Way

### ISSUE THREAD

**Issue by ynamiki** [vlsi/ksar#22]
A version number is defined in two locations:

- build.gradle -- for an artifact (a file name etc.)
- src/main/resources/kSar.version -- for AboutBox (only "x.y.z" format is accepted, no -SNAPSHOT)

The version should be defined in only one place.

**Comment by Pitterling** [comment]
@ynamiki What about using kSar.version also in the future and read this file within build.gradle to get the version number, like described here:
[external version file read by build.gradle](https://stackoverflow.com/questions/21405457/autoincrement-versioncode-with-gradle-extra-properties) ?

**Comment by ynamiki** [comment]
@Pitterling Thanks, I have updated the build script to generate kSar.version automatically.
This is the opposite approach to your comment.
I decide to use build.gradle as an input because kSar.version accepts only `x.y.z` format while the version in build.gradle has no such restriction.
