### ISSUE TITLE
Devices (Block) IO graph not shown for all devices 

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#234]
new version of ubuntu sysstat, and the devices are incomplete again. kSar for example shows the I/O to sdc device, but doesn't show individually the devices sdc1 and sdc2.
[ksaroutput.20210512100605.txt.zip](https://github.com/vlsi/ksar/files/4677927/ksaroutput.20200525123402.zip)

08:00:07 sdc 47.75 1132.35 859.64 0.00 41.72 0.11 1.93 4.33
08:00:07 sdc1 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
08:00:07 sdc2 47.34 1132.35 859.64 0.00 42.08 0.09 1.93 4.31
08:10:07 sdc 17.41 261.53 150.95 0.00 23.69 0.02 0.86 1.39
08:10:07 sdc1 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
08:10:07 sdc2 17.25 261.53 150.95 0.00 23.91 0.01 0.85 1.37

linked to #210

**Comment by Pitterling** [comment]
only sdXX devices
[ksaroutput.sdxx.txt](https://github.com/vlsi/ksar/files/6801667/ksaroutput.sdxx.txt)

partitions are missing !!!

![image](https://user-images.githubusercontent.com/4181164/125294992-11641980-e325-11eb-8d91-2aa1ad6219a5.png)

**Comment by Pitterling** [comment]
@vlsi would need your help as this looks like related to NaturalComparator.java .. skipping the sdXX-partitions ...

**Comment by vlsi** [comment]
```
sdc1 vs sdc ==> expected: <1> but was: <0>
Expected :1
Actual   :0
```

So there's something wrong with `NaturalComparator` indeed
