### ISSUE TITLE
Errors in reported memory

### ISSUE THREAD

**Issue by dormant** [vlsi/ksar#259]
I have just started using sysstat/sar/ksar, so might be doing something stupid. But my plots of memory usage are nothing like reality.

This is what sar reports:

$ sar -r -f /var/log/sysstat/sa10
Linux 5.18.0-2-amd64 (opsproc3) 	10/08/22 	_x86_64_	(12 CPU)

00:00:02    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
00:10:01      2751536  20160848  11453448     35.25   1807816  13886772  17495276     52.24   5863556  20914168      5264
00:20:01      2722236  20133256  11479196     35.33   1810128  13886860  17628556     52.64   5866120  20957396      4776
00:30:01      2725008  20157920  11456356     35.26   1812612  13905736  17495656     52.24   5869744  20953420      3980

And this is from ksar:

![Screenshot_2022-08-11_09-10-42](https://user-images.githubusercontent.com/156362/184141924-77caa540-cd7e-4d8d-b3e8-e8ea519c8809.png)

**Comment by PeterPitterling** [comment]
ksar 5.0.6 is ancient. This is a fork from an even later version 5.1.beta-* and further developed in the past years.
We don't give support for this old version. I would strongly recommend to use a newer build https://github.com/vlsi/ksar/releases/tag/v5.2.4-snapshot.10-gf068072 or even better take the last source and build yourself.
