### ISSUE TITLE
use Gradle 2.1 or higher ?

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#26]
cancelation of a DEBUG session gives me this error message

![image](https://cloud.githubusercontent.com/assets/4181164/15483943/c8106a0e-2137-11e6-8fa5-fe33c4638fb7.png)

although a newer version of gradle is in my repository directory .. it seems it takes the one under my user directory .. is this because of this definition in the gradle-wrapper.properties?

.\ksar-java\gradle\wrapper\gradle-wrapper.properties

```
#Wed Apr 27 22:26:08 JST 2016
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.0-bin.zip
```

**Comment by vlsi** [comment]
@Pitterling, I've updated gradle to 2.13 in https://github.com/vlsi/ksar/commit/7122bfd77052823c78ff74db3e3063f23ad2cfef

Can you please try again?

**Comment by Pitterling** [comment]
@vlsi, It's fixed now. Thx.
I'm still wondering why there is a fixed dependencies bw. the repo and a gradle version.

**Comment by vlsi** [comment]
@Pitterling , gradle version is specified in the git repository so everybody has the same gradle version, thus much less number of "works on my machine/gradle version" issues.
