### ISSUE TITLE
Logging - migrate from log4j to logback

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#263]

**Comment by vlsi** [comment]
I am not sure I would have time to implement this, however, I would support the migration.

**Comment by Pitterling** [comment]
ah ok, i thought you worked already on this topic

> @Pitterling , I'm inclined to switch from log4j2 to logback if you don't mind.

_Originally posted by @vlsi in https://github.com/vlsi/ksar/issues/256#issuecomment-1210474204_
