### ISSUE TITLE
CentOS 7 - SysStat 10.1.5-19.el7 : nothing in some graph

### ISSUE THREAD

**Issue by Tirguy** [vlsi/ksar#264]
Hello,

My configuration : 
- Linux CentOS 7.9.2009
- SysStat version 10.1.5-19.el7 
- KSar last version on Linux Ubuntu 20.4 (Java 11)

Sysstat takes a new measurement every minute and generates a new sarXX file every day at 23:59 

When i want to load in KSar the sar file, nothing appears... or almost !!!

I do not have anything on the CPU graph, Device Block graph, Interface Error and trafic graph, Process graph, Swap graph...
Whereas it seems to have a graph for Kernel VFS, Load, Sockets graph (NB: KMem graph just make appear the memory evolution, but du not graph anything on the cache/buffer/active/dirty graph).

Here is the beginning of the SAR file : 

`
Linux 3.10.0-1160.53.1.el7.x86_64 (prjpgsa002) 	01/03/23 	_x86_64_	(8 CPU)

00:00:01        CPU      %usr     %nice      %sys   %iowait    %steal      %irq     %soft    %guest    %gnice     %idle
00:01:01        all      0,06      0,00      0,15      0,00      0,00      0,00      0,00      0,00      0,00     99,78
00:01:01          0      0,12      0,00      0,22      0,00      0,00      0,00      0,00      0,00      0,00     99,67
00:01:01          1      0,08      0,00      0,17      0,00      0,00      0,00      0,00      0,00      0,00     99,75
00:01:01          2      0,05      0,00      0,08      0,00      0,00      0,00      0,00      0,00      0,00     99,87
00:01:01          3      0,03      0,00      0,47      0,00      0,00      0,00      0,00      0,00      0,00     99,50
00:01:01          4      0,03      0,00      0,05      0,00      0,00      0,00      0,00      0,00      0,00     99,92
00:01:01          5      0,03      0,00      0,05      0,00      0,00      0,00      0,00      0,00      0,00     99,92
00:01:01          6      0,10      0,00      0,08      0,00      0,00      0,00      0,00      0,00      0,00     99,82
00:01:01          7      0,07      0,00      0,10      0,00      0,00      0,00      0,00      0,00      0,00     99,83
00:02:01        all      0,07      0,00      0,16      0,00      0,00      0,00      0,00      0,00      0,00     99,77
00:02:01          0      0,05      0,00      0,08      0,00      0,00      0,00      0,00      0,00      0,00     99,87
`

Does some people have this problem too ? 

With an old KSar version (https://github.com/ppalucha/ksar2) i have this screen : 

![image](https://user-images.githubusercontent.com/39098909/210856997-4ce2de39-a309-4536-a09a-aa3f2435034a.png)

Whereas with this version, i have this screen : 

![image](https://user-images.githubusercontent.com/39098909/210857245-187392e5-e95d-4577-9c10-cf04a86dad31.png)

Is it an issue ?

Thank's for help,

Thierry

**Comment by Pitterling** [comment]
Please provide such a file.

when you refer to latest kSar version, do you mean the latest snapshot version?

**Comment by Tirguy** [comment]
I mean "the last release" ;-)
Not the last snapshot because i do not have something to make it :-( 

Do you really want all the file ?

**Comment by Tirguy** [comment]
[prjpgsa001_sa03.sar.zip](https://github.com/vlsi/ksar/files/10361936/prjpgsa001_sa03.sar.zip)

Here is an exemple....

**Comment by Pitterling** [comment]
Your file format and content is in french. That is not expected by kSar.

- your decimal separator is a comma instead of point
- your "Average" lines are also translated 

Seems like you adjusted how SAR data is collected. All errors should be shown by the ksar_all.log file. Do you have such a file?

Snapshot versions are also provided on the [Release page](https://github.com/vlsi/ksar/releases). But the last available is also 2y old and does not contain all changes afterwards.

I compiled a version which is handling your french version as well .. give it a try and provide feedback. Furthermore it seems your example file is not complete as it does not contain the last lines (Summary/Resume). Maybe you can provide such a file again to check if these lines are also handled correctly.

[ksar-5.2.4-SNAPSHOT-all.zip](https://github.com/vlsi/ksar/files/10366454/ksar-5.2.4-SNAPSHOT-all.zip)

**Comment by Pitterling** [comment]
@Tirguy Any feedback to my last comment?

**Comment by Tirguy** [comment]
Sorry... was sick and in bed since 2 weeks :-( 

Unfortunately, I don't have control over the way sar files are built on our servers: it's a separate team that manages that...
Indeed, the file is in a "French" format.

I compiled a version which is handling your french version as well : thank's ;-)

Apparently, this version seems to handle correctly the import of this type of file... everything seems to be back in order :-D

Here is the ksar_all.log file that was generated by this special version.
[ksar_all.log](https://github.com/vlsi/ksar/files/10467017/ksar_all.log)

The example file is not complete as it does not contain the last lines
What should I find in this file? What are the last lines I should find?

**Comment by Pitterling** [comment]
The last lines in a sar file are the summary lines. In french it would be "Résumé:"

Would be great to get a sar file with "Moyenne " and ""Résumé:"

Thanks

**Comment by Tirguy** [comment]
It's strange...
I've search an example in all computer from my dev' plateform, i just have "Moyenne" ("average" in english) at the end of file.
Here is 3 differents files from different server on my dev' plateform : 
- CentOS 6.4
- Centos 7.9
- Rocky8

Not sur that there is many activity on them ;-)  

[sar_french.zip](https://github.com/vlsi/ksar/files/10521960/sar_french.zip)

**Comment by Pitterling** [comment]
cause you are not collecting all statistics. For your stats only Average will be appended. "FILESYSTEM" stats and a few others hat "Summary" instead of "Average"
