### ISSUE TITLE
Timezone - How does it work

### ISSUE THREAD

**Issue by apachipa** [vlsi/ksar#282]
Hi ksar team, 

If i copy sar historical data from "/var/log/sa" on to my local desktop and upload data to analyze, will ksar convert data to local timezone on my laptop or does it keep data time zones/timestamps as is ?

Cheers,
Ash

**Comment by Pitterling** [comment]
SAR data don't contain time zone information.
No date/time conversion is happening by kSar.

Date is taken from 1st line and times from the statistics lines.

**Comment by apachipa** [comment]
Thank you.
