### ISSUE TITLE
Graph CPU doesn't show used % but anything else show up.

### ISSUE THREAD

**Issue by mungming7594** [vlsi/ksar#285]
Hello, 

My configuration:

-Windows 11 Home Single Language
-Ksar-5.2.4
-java version "1.8.0_391"

CPU Graph not show used%
![cpu graph not show](https://github.com/vlsi/ksar/assets/144981810/053340b6-a0b7-41eb-8329-d392db8a7303)

Kmem
![kmem](https://github.com/vlsi/ksar/assets/144981810/4a6f55bb-7d79-448f-bfe8-a547b55c3e75)

KSwap
![kswap](https://github.com/vlsi/ksar/assets/144981810/8a3cacbb-d71c-45d0-942f-25af4b90a935)

Load
![load](https://github.com/vlsi/ksar/assets/144981810/5c342cc6-842f-4edd-8311-ff98d73b4c4c)

Thank's for help,
mungming7594

**Comment by Pitterling** [comment]
Please provide your SAR file.

**Comment by mungming7594** [comment]
[sar01_rename.zip](https://github.com/vlsi/ksar/files/13262587/sar01_rename.zip)

**Comment by PeterPitterling** [comment]
zip file is not valid

**Comment by Pitterling** [comment]
zip file is not valid

**Comment by mungming7594** [comment]
It not a zip file but the file type does not support here. 
![image](https://github.com/vlsi/ksar/assets/144981810/28eb40da-14b2-46e0-b519-7599070ddc89)

**Comment by Pitterling** [comment]
your uploaded file is not a zip file, but a rar file !!! You could also upload txt files --> sar01_rename.txt would have been valid.

To your problem. Your file just works fine, therefore which version are you using?
Also, please provide a trace output "java -jar ksar-5.2.4.jar -trace" attach the resulting ksar_all.log file.

**Comment by mungming7594** [comment]
ksar_all.log
[ksar_all.log](https://github.com/vlsi/ksar/files/13330604/ksar_all.log)

**Comment by Pitterling** [comment]
You only traced the program start, but not the processing of your file.

Nevertheless you are not running the [latest version](https://github.com/vlsi/ksar/releases/latest) (yours 5.2.4-b285_g4bbaff17-SNAPSHOT). Please update and try again
