### ISSUE TITLE
No Load chart with RedHat 7

### ISSUE THREAD

**Issue by GaboFDC** [vlsi/ksar#31]
After processing a sar file from a RHEL 7 with sysstat-10.1.5-7.el7 the load graphic is not generated:

![screenshot from 2016-08-05 11-39-50](https://cloud.githubusercontent.com/assets/1425500/17443688/9fed4c96-5b01-11e6-8646-57fc37b3e33a.png)

**Comment by Pitterling** [comment]
this is due to the metric "blocked" which has been introduced in sysstat 9.1.7

> 2010/12/26: Version 9.1.7:
> Added a new metric (number of tasks waiting for I/O) to sar -q.

load graph definition does not expect this column

btw, you are not using the latest version 5.2, otherwise CPU node "all" would be listed as first leaf in the tree

**Comment by vlsi** [comment]
@Pitterling , thanks for the quick fix.
I've released https://github.com/vlsi/ksar/releases/tag/v5.2.1
