### ISSUE TITLE
How to specify "Plot ordering" ?

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#34]
Plots are ordered alphabetically and not by XML definition

![image](https://cloud.githubusercontent.com/assets/4181164/17459345/a1569852-5c33-11e6-8177-1264db7a0479.png)

Would it be possible to specify the ordering of Plots ? e.g. tps, sector, service ...

**Comment by Pitterling** [comment]
at the moment it is sorted by character - UPPER chars first, lower chars later on

![image](https://cloud.githubusercontent.com/assets/4181164/17781668/90a24f42-6570-11e6-9d03-c44ece66b926.png)


TODO: should be changed in a way, that XML chart definition defines also the ordering

**Comment by vlsi** [comment]
This makes sense

**Comment by Pitterling** [comment]
@vlsi  it has been recently introduced - [GraphConfig.java](ksar/src/main/java/net/atomique/ksar/XML/GraphConfig.java)

changing from HashMap to SortedMap for Plots and Stacks
