### ISSUE TITLE
missing Fixes from ynamikis fork of ksar

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#4]
@ynamiki, before you started to contribute to this fork, you had a couple of more fixes within your direct fork of ksar which are missing now here:

- Fix SimpleDateFormat parse with AM/PM format
- Fix #1, non-effective assignment at PlotConfig#setSize(String)
- Cleanup + Generics

Is this something you want to apply here as well?

**Comment by ynamiki** [comment]
I have cherry-picked the commits at my direct fork, including the pull request by @scr34m.
