### ISSUE TITLE
Timezone in Window title is wrong - showing local timezone

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#42]
DateTime is shown in the window title.

In this example .. data has been collected on system with GMT timezone

![image](https://cloud.githubusercontent.com/assets/4181164/18013304/bb212bbe-6bbd-11e6-97a0-135b6c692732.png)

AllParser.java --> setDate is just calling SimpleDateFormat, which is using the current LOCALE, if nothing is specified.

```
            dateSimple1 = new SimpleDateFormat(dateFormat).parse(s);            
            cal.setTime(dateSimple1);
            day=cal.get(cal.DAY_OF_MONTH);
            month=cal.get(cal.MONTH)+1;
            year=cal.get(cal.YEAR);
            dateSimple2 = new SimpleDateFormat(dateFormat).parse(sarStartDate);
            dateSimple3 = new SimpleDateFormat(dateFormat).parse(sarEndDate);
```

Timezone, LOCALE information could not be extracted from the SAR data, therefore the time should just be represented as is, without any timezone information.

**Comment by vlsi** [comment]
Just in case: am I right there are issues when sar log spans 00:00? (as far as I can remember, charts cannot dislpay multi-day data)

**Comment by Pitterling** [comment]
@vlsi don't think this is an issue. I have 2 sar files, which both don't span 00:00, but i used the "append" functionality and this is painted correctly. Also internally its using Date+Time ...
What is not working, is to append in the wrong order .. 1.) Day2 2.) Day1 ... this will only show the first day.

**Comment by Pitterling** [comment]
@vlsi you are right, spans are not handled correctly - the date change is not reflected, it is added to the chart with the old date. It is not shown originally, because the plot is adjusted to a different time window. Once you zoom out, you see the other data as well.

Adding data from different days without any span is handled correctly.

I'm currently working on the date/time topic and hope to get it done soon.
