### ISSUE TITLE
Linux: IO chart is reporting bytes, were data is reported as sector

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#5]
Hi, the IO chart is showing bread/s and bwrtn/s in the legend and also the chart axis title is byte.
In fact the data delivered by sar is in sector .. bread/s = sector/s = 512 byte

![image](https://cloud.githubusercontent.com/assets/4181164/14461528/4b78da24-00c3-11e6-8a5b-e9ba60224478.png)

> Report I/O and transfer rate statistics. The following values are displayed: 
> tps 
> Total number of transfers per second that were issued to physical devices. A transfer is an I/O request to a physical device. Multiple logical requests can be combined into a single I/O request to the device. A transfer is of indeterminate size.
> 
> rtps 
> Total number of read requests per second issued to physical devices.
> 
> wtps 
> Total number of write requests per second issued to physical devices.
> 
> **bread/s** 
> Total amount of data read from the devices in **blocks per second**. Blocks are equivalent to sectors with 2.4 kernels and newer and therefore have **a size of 512 bytes**. With older kernels, a block is of indeterminate size.
> 
> **bwrtn/s** 
> Total amount of data written to devices in blocks per second.

**Comment by vlsi** [comment]
Hi, can you please attach the file just in case?

**Comment by Pitterling** [comment]
[test01_sar.zip](https://github.com/vlsi/ksar/files/215287/test01_sar.zip)

this is really a hugh file .. in principal you could use any file. thx

**Comment by Pitterling** [comment]
I adjusted the original issue text .. i pasted a wrong screenshot showing the device stats instead of the IO report data. Now i included the man page section -> bread/s = sector/s = 512 byte

**Comment by vlsi** [comment]
Closed in #33
