### ISSUE TITLE
Change disk names

### ISSUE THREAD

**Issue by GaboFDC** [vlsi/ksar#60]
Feature Request.

Currently the disk related graphics (Devices) show usage per device showing the direct device name i.e (dev253-2)

Is it possible to add an option to change those names to the mount points for a better understanding and visualization. To get the actual mount point of each device, I see that there could be 2 options

1. asking the user to put the real name
2. asking the user to put the output of a lsblk command, and getting the real names from that output.

**Comment by Pitterling** [comment]
would be better done during datacollection by sar? Also it would be just a name mapping 1:1. KPIs will be not be combined in case of lvol stripe etc.

**Comment by lingyanmeng** [comment]
To collect the disk information with label, you can use "-P" for sa2, for example in CentOS:
Edit the sysstat configuration file:
`vi /etc/cron.d/sysstat`
Change the line that reads
`53 23 * * * root /usr/lib64/sa/sa2 -A`
to
`53 23 * * * root LANG=en_US; /usr/lib64/sa/sa2 -A -p`

The LANG setting is also needed, as ksar cannot parse other languages.
