### ISSUE TITLE
There is a mismatch on interface traffic chart

### ISSUE THREAD

**Issue by ntthvan** [vlsi/ksar#64]
There is a mismatch on interface traffic chart. In sar data, rxkB/s=791.50 but the chart show 791.50/1000.

00:00:01        IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
00:10:02           lo   1507.50   1507.50    791.50    791.50      0.00      0.00      0.00
00:10:02         eth0    225.45    212.00     65.82     63.06      0.00      0.00      0.02

**Comment by Pitterling** [comment]
Did you check the axis unit? this is actually dynamic and might show MB/s ??

**Comment by ntthvan** [comment]
Hi Pitterling,
The axis unit shows KB. I think it should show KB/s. you can see the chart as the below link.
![image](https://cloud.githubusercontent.com/assets/26480653/24137578/f687a198-0e46-11e7-9963-780dfc03f17a.png)
The data on sar file:
![image](https://cloud.githubusercontent.com/assets/26480653/24137735/afdf260c-0e47-11e7-8cf0-dd6fc3afbe9f.png)

thanks.

**Comment by Pitterling** [comment]
please provide the sar file.

**Comment by ntthvan** [comment]
As the below attachment:
[sar_data_09_25_2014.txt](https://github.com/vlsi/ksar/files/857461/sar_data_09_25_2014.txt)

**Comment by Pitterling** [comment]
will look into this .. might take a while

**Comment by Pitterling** [comment]
small values <1 MB are affected - this also applies for any other chart using factor=1024

Problems resides here - [public class IEEE1541Number extends NumberFormat](https://github.com/vlsi/ksar/blob/95f6afc963f9564a2e9e29124fb3926df443c9c8/src/main/java/net/atomique/ksar/Graph/IEEE1541Number.java)

**Comment by ntthvan** [comment]
Great! Thanks Pitterling for your investigation.
When do we have new version include fix for this?
thanks.

**Comment by Pitterling** [comment]
new release has been published
