### ISSUE TITLE
Migrate build to maven

### ISSUE THREAD

**Issue by vlsi** [vlsi/ksar#7]

**Comment by ynamiki** [comment]
@vlsi  Do you prefer Maven to Gradle? I am interested in Gradle for its simplicity.

**Comment by vlsi** [comment]
Both work for me.

I want to cover publishing snapshots/releases to maven central, and releases to github releases.

**Comment by ynamiki** [comment]
Should we keep the current directory structure or reorganize it into the Maven standard structure?

**Comment by vlsi** [comment]
I think we'd better reorganize.

I'm not fluent in gradle, however feel free to migrate to gradle if you wish.
In any case, I would prefer standard layout.

**Comment by vlsi** [comment]
@ynamiki , Let's go with gradle (otherwise I'll never start using gradle).
The question is regarding groupid/artifactid.

Are you fine with `com.github.vlsi.ksar:ksar`?

**Comment by ynamiki** [comment]
@vlsi Could you please review #19?

groupId/artifactId is `com.github.vlsi:ksar`. Should I put "ksar" in both groupId and artifactId as you described?

**Comment by vlsi** [comment]
I would prefer having ksar in groupid just in case there will be more artifacts

**Comment by ynamiki** [comment]
Sure, I have update the groupId, see #19.
