### ISSUE TITLE
Unable to extract from SLES 12 SP2 running Linux 4.4.49-92.11-default

### ISSUE THREAD

**Issue by pomusa** [vlsi/ksar#93]
Hello,

i am unable to run any of the latest 5.2.x version of ksar to gather the report from the sar file. However, i am able to get almost all the data with the exception of network device on the ksar 5.0.6 version. i have attached a copy of my sar file.

[sar16.zip](https://github.com/vlsi/ksar/files/1008224/sar16.zip)

**Comment by Pitterling** [comment]
Hi, linux kernel version does not matter. sysstat version is only relevant .. i assume its 10.2.5

I'm able to read your data .. you need to specify the correct date/time value:

![image](https://cloud.githubusercontent.com/assets/4181164/26162547/57ed45f2-3b27-11e7-92a2-8e7fca2d9409.png)

Header title should change during parsing .. it runs for awhile and you should get the desired output.
![image](https://cloud.githubusercontent.com/assets/4181164/26162633/9331edac-3b27-11e7-94db-7a282ad550e7.png)
