### ISSUE TITLE
cpu parsing on AIX error

### ISSUE THREAD

**Issue by elkrieg** [vlsi/ksar#97]
5.0.6 parsed AIX CPU well, but in latest versions tables like

00:00:00    %usr    %sys    %wio   %idle   physc   %entc
00:01:00       9       1       1      89    1.00    16.7

Are not recognized as CPU

**Comment by Pitterling** [comment]
Please upload an example file.

**Comment by elkrieg** [comment]
Fix provided in #99
Exqample file attached

**Comment by elkrieg** [comment]
[sarDR15.txt](https://github.com/vlsi/ksar/files/1161391/sarDR15.txt)
